[formatter.nix]
command = "nixfmt"
options = ["-s", "-w", "120"]
includes = ["*.nix"]

[formatter.nu]
command = "nufmt"
includes = ["*.nu"]

[formatter.md]
command = "oxfmt"
includes = ["*md"]

[formatter.json]
command = "oxfmt"
options = []
includes = ["*.json"]
excludes = ["secrets/**", "modules/desktop/audio/**"]
