# Appearance
window_padding_width 4

# Font Configuration
font_family      JetBrains Mono NL 
bold_font        Jetbrains Mono NL Bold
italic_font      JetBrains Mono NL Italic
font_size 11.0

# Exra
scrollback_lines 4096
enable_audio_bell no
strip_trailing_spaces smart

include ./theme.conf