# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "UUID=d584e71f-2c5d-41e2-95e7-ed41f0833e25";
    fsType = "bcachefs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8841-1618";
    fsType = "vfat";
  };

  fileSystems."/docker" = {
    device = "/dev/disk/by-uuid/d7c1613f-24dc-434a-bbb0-0051ea4524ca";
    fsType = "ext4";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-0ea29a46a357.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-0ea50d01088e.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-0fea806a6c5c.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-3ae328ad2eb5.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-3f16f478984d.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-63f977221584.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-806c86214a4b.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-efef802f9a95.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.fabric.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
