name: "cachix"
on:
  push:
  pull_request:
jobs:
  nixos-unstable:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: karitham
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build packages and push to cachix
        # one of the most heavily configured system with most of the software
        run: nix build --accept-flake-config .#nixosConfigurations.belaf.config.system.build.toplevel
