name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: cachix/cachix-action@v16
        with:
          name: karitham
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix profile install nixpkgs#nodejs # required for update-flake-lock action
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Automated: Update flake.lock"
          pr-labels: |
            dependencies
            automated
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build --accept-flake-config .#nixosConfigurations.kiwi.config.system.build.toplevel

  cache-latest:
    name: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: cachix/cachix-action@v16
        with:
          name: karitham
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build --accept-flake-config .#nixosConfigurations.kiwi.config.system.build.toplevel
